---
output: pdf_document
---

```{r setup, include=FALSE}
library(sqldf)
library(mice)
library(gvlma)
```

```{r include=TRUE} 
ccwo <- read.csv("/Users/fernandooliveira/workspaces/mestrado/Experimento/masters_experiment_analysis/dataset.csv")
ccwo$Minutes[ccwo$Minutes < 5] <- NA
```

```{r include=TRUE}
md.pattern(ccwo)
```

```{r echo=FALSE, include=TRUE}
ccid <- mice(ccwo, m=5, maxit = 50, method = 'pmm', seed=500)
ccwocd <- complete(ccid,2)
```


```{r echo=FALSE, include=TRUE}
totalTime <- sqldf("select Replica, Id, SetOfTasks, 
                    Technique, sum(Trials) as Trials, sum(Minutes) as Time 
                    from ccwocd 
                    group by Replica, Id,SetOfTasks, Technique")
```

```{r echo=FALSE, include=TRUE}
totalTime
boxplot(totalTime$Time~totalTime$Technique,outline=F,ylab="Minutos", #names=c("Disciplinado", "N達o disciplinado")
        names=c("Disciplined", "Undisciplined")
        )
```

```{r echo=FALSE, include=TRUE}
totalTime3 <- sqldf("select Replica, Id, Tasks, Technique, sum(Trials) as Trials, sum(Minutes) as Time 
                    from ccwocd 
                    group by Replica, Id, Tasks, Technique")
totalTime3$Tasks <- as.numeric(totalTime3$Tasks)
totalTime3$Tasks <- ifelse(totalTime3$Tasks == 4, 1, totalTime3$Tasks)
totalTime3$Tasks <- ifelse(totalTime3$Tasks == 5, 2, totalTime3$Tasks)
totalTime3$Tasks <- ifelse(totalTime3$Tasks == 6, 3, totalTime3$Tasks)
totalTime3$Tasks <- ifelse(totalTime3$Tasks == 1, 'T1', totalTime3$Tasks)
totalTime3$Tasks <- ifelse(totalTime3$Tasks == 2, 'T2', totalTime3$Tasks)
totalTime3$Tasks <- ifelse(totalTime3$Tasks == 3, 'T3', totalTime3$Tasks)

#totalTime3$Technique <- ifelse(totalTime3$Technique == 'U', 'ND', 'D')
totalTime3 <- sqldf("select Replica, Tasks, Technique, sum(Trials) as Trials, sum(Time) as Time 
                    from totalTime3 
                    group by Replica, Tasks, Technique")

boxplot(totalTime3$Time~totalTime3$Technique+totalTime3$Tasks,outline=F,
        #ylab="Minutos"
        ylab="Minutes"
        )
```

```{r echo=FALSE, include=TRUE}
totalTime3 <- sqldf("select Replica, Id, Tasks, Technique, sum(Trials) as Trials, sum(Minutes) as Time 
                    from ccwocd 
                    group by Replica, Id, Tasks, Technique")
totalTime3$Tasks <- as.numeric(totalTime3$Tasks)
totalTime3$Tasks <- ifelse(totalTime3$Tasks == 4, 1, totalTime3$Tasks)
totalTime3$Tasks <- ifelse(totalTime3$Tasks == 5, 2, totalTime3$Tasks)
totalTime3$Tasks <- ifelse(totalTime3$Tasks == 6, 3, totalTime3$Tasks)
totalTime3$Tasks <- ifelse(totalTime3$Tasks == 1, 'T1', totalTime3$Tasks)
totalTime3$Tasks <- ifelse(totalTime3$Tasks == 2, 'T2', totalTime3$Tasks)
totalTime3$Tasks <- ifelse(totalTime3$Tasks == 3, 'T3', totalTime3$Tasks)

#totalTime3$Technique <- ifelse(totalTime3$Technique == 'U', 'ND', 'D')
totalTime3 <- sqldf("select Replica, Tasks, Technique, sum(Trials) as Trials, sum(Time) as Time 
                    from totalTime3 
                    group by Replica, Tasks, Technique")
totalTime3
boxplot(totalTime3$Trials~totalTime3$Technique+totalTime3$Tasks,outline=F,
        #ylab="Tentativas"
        ylab="Tries"
        )
ccwocd
t1 <- sqldf("select Replica, Tasks, Minutes, Time from ccwocd WHERE Tasks = 'T1' OR Tasks = 'T4'")
t1
t2 <- sqldf("select Replica, Tasks, Minutes, Time from ccwocd WHERE Tasks = 'T2' OR Tasks = 'T5'")
t2
t3 <- sqldf("select Replica, Tasks, Minutes, Time from ccwocd WHERE Tasks = 'T3' OR Tasks = 'T6'")
t3
mean(t1$Time)
mean(t2$Time)
mean(t3$Time)
```

```{r echo=FALSE, include=TRUE}
totalTime2 <- sqldf("select Replica, Id, SetOfTasks, 
                    Technique, sum(Trials) as Trials, sum(Minutes) as Time 
                    from ccwocd 
                    group by Replica, Id,SetOfTasks, Technique")
totalTime2$Time <-ifelse(totalTime2$Technique == "D", - totalTime2$Time, totalTime2$Time)
totalTime2 <- sqldf("select Id, sum(Time) as Time 
                    from totalTime2 
                    group by Id, Replica")

d <- density(totalTime2$Time, na.rm=TRUE) # returns the density data
plot(d, xlab="Participantes = 30; Largura de banda = 8.675",
     ylab="Densidade",
     main=expression(T[nd] - T[d]))

```

```{r echo=FALSE, include=TRUE}
boxplot(totalTime3$Trials~totalTime3$Technique+totalTime3$Tasks,outline=F, at=c(3,4,5,6,7,8),xlim=c(0, 9), width=c(0.25,0.25,0.25,0.25,0.25,0.25),
        #ylab="Tentativas"
        ylab="Tries"
        )
totalTrials <- sqldf("select Replica, Id, SetOfTasks,
                      Technique, sum(Trials) as Trials
                      from ccwocd
                      group by Replica, Id,SetOfTasks, Technique")
boxplot(totalTrials$Trials~totalTrials$Technique, add=TRUE, at=c(1,2), width=c(0.1,0.1), col="grey",
        #names=c("Disciplinado", "N達o disciplinado")
        names=c("D.Tt", "U.Tt")
        )
```

```{r echo=FALSE, include=TRUE}
totalTime <- sqldf("select Replica, Id, SetOfTasks, 
                    Technique, sum(Trials) as Trials, sum(Minutes) as Time 
                    from ccwocd 
                    group by Replica, Id,SetOfTasks, Technique")

boxplot(totalTime3$Time~totalTime3$Technique+totalTime3$Tasks,outline=F,at=c(3,4,5,6,7,8), xlim=c(0, 9), ylim=c(10,100),
        width=c(0.25,0.25,0.25,0.25,0.25,0.25),
        #ylab="Minutos"
        ylab="Minutes"
        )

boxplot(totalTime$Time~totalTime$Technique, outline=F, at=c(1,2), width=c(0.1,0.1), col="grey", add=TRUE,
        names=c("D.Tt", "U.Tt")
        )

```

```{r include=TRUE}
totalTrials <- sqldf("select Replica, Id, SetOfTasks,
                      Technique, sum(Trials) as Trials
                      from ccwocd
                      group by Replica, Id,SetOfTasks, Technique")

totalTrials
boxplot(totalTrials$Trials~totalTrials$Technique, 
        #names=c("Disciplinado", "N達o disciplinado")
        names=c("Disciplined", "Undisciplined")
        )
```

```{r echo=FALSE, include=TRUE}
#names=c('Depreciado', 'De terceiros', 'Rejeitado', 'Aceito')
names=c('Deprecated', 'Third parties', 'Rejected', 'Accepted')
values=c(7, 11, 19, 63)
barplot(values,names.arg=names)
text(0.75,5, '7%',cex = 0.7)
text(1.95,8, '11%',cex = 0.7)
text(3.1,16, '19%',cex = 0.7)
text(4.32,60, '63%',cex = 0.7)

```

```{r echo=FALSE, include=TRUE}
  boxplot(totalTime3[totalTime3$Tasks == 'T1', ]$Time~totalTime3[totalTime3$Tasks == 'T1', ]$Technique+totalTime3[totalTime3$Tasks == 'T1', ]$Tasks,outline=F,
        ylab="Minutos"
        #ylab="Minutes"
        )
```
```{r echo=FALSE, include=TRUE}
totalTime2 <- sqldf("select Replica, Id, SetOfTasks, 
                    Technique, sum(Trials) as Trials, sum(Minutes) as Time 
                    from ccwocd Where Tasks = 'T1' or Tasks = 'T4'
                    group by Replica, Id,SetOfTasks, Technique")
totalTime2$Time <-ifelse(totalTime2$Technique == "D", - totalTime2$Time, totalTime2$Time)
totalTime2 <- sqldf("select Id, sum(Time) as Time 
                    from totalTime2 
                    group by Id, Replica")

d <- density(totalTime2$Time) # returns the density data 
plot(d,  xlab="Participantes = 30; Largura de banda = 4.082",
     ylab="Densidade",
     main=expression(T[nd] - T[d]))

```

```{r include=TRUE}
totalTime <- sqldf("select Replica, Id, SetOfTasks, 
                    Technique, sum(Trials) as Trials, sum(Minutes) as Time 
                    from ccwocd where Tasks = 'T1' OR Tasks = 'T4'
                    group by Replica, Id,SetOfTasks, Technique")




#totalTime$Trials <- with(totalTime, (Trials - min(Trials)) / (max(Trials) - min(Trials)))
#totalTime$Time <- with(totalTime, (Time - min(Time)) / (max(Time) - min(Time)))
#totalTime$Trials <- with(totalTime, sqrt(Trials))
#totalTime$Time <- with(totalTime, sqrt(Time))
totalTime$Time <- with(totalTime, log2(Time))



```

```{r include=TRUE}
totalTime$Replica = as.factor(totalTime$Replica)
totalTime$Id = as.factor(totalTime$Id)
totalTime$SetOfTasks = as.factor(totalTime$SetOfTasks)
totalTime$Technique = as.factor(totalTime$Technique)
```

```{r include=TRUE}
totalTime.gvlma = gvlma(lm(Time ~ Technique, data=totalTime))
summary(totalTime.gvlma)
```

```{r include=TRUE}
summary(aov(lm(Time ~ Technique, data=totalTime)))
```

```{r echo=FALSE, include=TRUE}
  boxplot(totalTime3[totalTime3$Tasks == 'T1', ]$Trials~totalTime3[totalTime3$Tasks == 'T1', ]$Technique+totalTime3[totalTime3$Tasks == 'T1', ]$Tasks,outline=F,
        #ylab="Minutos"
        ylab="Tentativas"
        )
```

```{r include=TRUE}
totalTrials <- sqldf("select Replica, Id, SetOfTasks,
                      Technique, sum(Trials) as Trials
                      from ccwocd where Tasks = 'T1' OR Tasks = 'T4'
                      group by Replica, Id,SetOfTasks, Technique")
totalTrials$Trials <- with(totalTrials, Trials + 1)
totalTrials$Trials <- with(totalTrials, log2(Trials))
```

```{r include=TRUE}
totalTrials$Replica = as.factor(totalTrials$Replica)
totalTrials$Id = as.factor(totalTrials$Id)
totalTrials$SetOfTasks = as.factor(totalTrials$SetOfTasks)
totalTrials$Technique = as.factor(totalTrials$Technique)
```

```{r include=TRUE}
summary(aov(Trials ~ Replica + Replica:Id + SetOfTasks + Technique, data=totalTrials))
totalTrials.gvlma = gvlma(lm(Trials ~ Technique, data=totalTrials))
summary(totalTrials.gvlma)
```

```{r include=TRUE}
summary(aov(Trials ~ Technique, data=totalTrials))
```

```{r echo=FALSE, include=TRUE}
  boxplot(totalTime3[totalTime3$Tasks == 'T2', ]$Time~totalTime3[totalTime3$Tasks == 'T2', ]$Technique+totalTime3[totalTime3$Tasks == 'T2', ]$Tasks,outline=F,
        ylab="Minutos"
        #ylab="Minutes"
        )
```
```{r echo=FALSE, include=TRUE}
totalTime2 <- sqldf("select Replica, Id, SetOfTasks, Tasks, 
                    Technique, sum(Trials) as Trials, sum(Minutes) as Time 
                    from ccwocd Where Tasks = 'T2' or Tasks = 'T5'
                    group by Replica, Id,SetOfTasks, Technique")
totalTime2$Time <-ifelse(totalTime2$Technique == "D", - totalTime2$Time, totalTime2$Time)
totalTime2 <- sqldf("select Id, sum(Time) as Time 
                    from totalTime2 
                    group by Id, Replica")

d <- density(totalTime2$Time) # returns the density data 
plot(d,  xlab="Participantes = 30; Largura de banda = 5.528",
     ylab="Densidade",
     main=expression(T[nd] - T[d]))

```

```{r include=TRUE}
totalTime <- sqldf("select Replica, Id, SetOfTasks, 
                    Technique, sum(Trials) as Trials, sum(Minutes) as Time 
                    from ccwocd where Tasks = 'T2' OR Tasks = 'T5'
                    group by Replica, Id,SetOfTasks, Technique")

totalTime$Time <- with(totalTime, log2(Time))

```

```{r include=TRUE}
totalTime$Replica = as.factor(totalTime$Replica)
totalTime$Id = as.factor(totalTime$Id)
totalTime$SetOfTasks = as.factor(totalTime$SetOfTasks)
totalTime$Technique = as.factor(totalTime$Technique)
```

```{r include=TRUE}
totalTime.gvlma = gvlma(lm(Time ~ Technique + SetOfTasks, data=totalTime))
summary(totalTime.gvlma)
```

```{r include=TRUE}
summary(aov(lm(Time ~ Technique, data=totalTime)))
```

```{r echo=FALSE, include=TRUE}
kruskal.test(Time ~ Technique, data=totalTime)
```

```{r echo=FALSE, include=TRUE}
  boxplot(totalTime3[totalTime3$Tasks == 'T2', ]$Trials~totalTime3[totalTime3$Tasks == 'T2', ]$Technique+totalTime3[totalTime3$Tasks == 'T2', ]$Tasks,outline=F,
        #ylab="Minutos"
        ylab="Tentativas"
        )
```

```{r include=TRUE}
totalTrials <- sqldf("select Replica, Id, SetOfTasks,
                      Technique, sum(Trials) as Trials
                      from ccwocd where Tasks = 'T2' OR Tasks = 'T5'
                      group by Replica, Id,SetOfTasks, Technique")

totalTrials$Trials <-ifelse(totalTrials$Trials == 0, 1, totalTrials$Trials)
totalTrials$Trials <- with(totalTrials, log2(Trials))
```

```{r include=TRUE}
totalTrials$Replica = as.factor(totalTrials$Replica)
totalTrials$Id = as.factor(totalTrials$Id)
totalTrials$SetOfTasks = as.factor(totalTrials$SetOfTasks)
totalTrials$Technique = as.factor(totalTrials$Technique)
```

```{r include=TRUE}
summary(aov(Trials ~ Technique, data=totalTrials))
totalTrials.gvlma = gvlma(lm(Trials ~ Technique, data=totalTrials))
summary(totalTrials.gvlma)
```

```{r include=TRUE}
summary(aov(Trials ~ Technique, data=totalTrials))
```
```{r include=TRUE}
ss = summary(aov(Trials ~ Technique, data=totalTrials))[[1]]$"Sum Sq"
eta.sq = ss[1]/(ss[1] + ss[2])
print(paste0("The eta-squared is ",toString(round(eta.sq,3))))
```

```{r include=TRUE}
q <- TukeyHSD(aov(Trials~Technique, data=totalTrials))
q
```

```{r echo=FALSE, include=TRUE}
  boxplot(totalTime3[totalTime3$Tasks == 'T3', ]$Time~totalTime3[totalTime3$Tasks == 'T3', ]$Technique+totalTime3[totalTime3$Tasks == 'T3', ]$Tasks,outline=F,
        ylab="Minutos"
        #ylab="Minutes"
        )
```

```{r include=TRUE}
totalTime <- sqldf("select Replica, Id, SetOfTasks, 
                    Technique, sum(Trials) as Trials, sum(Minutes) as Time 
                    from ccwocd where Tasks = 'T3' OR Tasks = 'T6'
                    group by Replica, Id,SetOfTasks, Technique")

totalTime$Time <- with(totalTime, log2(Time))

```

```{r include=TRUE}
totalTime$Replica = as.factor(totalTime$Replica)
totalTime$Id = as.factor(totalTime$Id)
totalTime$SetOfTasks = as.factor(totalTime$SetOfTasks)
totalTime$Technique = as.factor(totalTime$Technique)
```

```{r include=FALSE}
totalTime.gvlma = gvlma(lm(Time ~ Technique, data=totalTime))
summary(totalTime.gvlma)
```

```{r include=TRUE}
summary(aov(lm(Time ~ Technique, data=totalTime)))
```

```{r include=TRUE}
ss = summary(aov(Time ~ Technique, data=totalTime))[[1]]$"Sum Sq"
eta.sq = ss[1]/(ss[1] + ss[2])
print(paste0("The eta-squared is ",toString(round(eta.sq,3))))
```

```{r include=TRUE}
q <- TukeyHSD(aov(Time~Technique, data=totalTime))
q
```

```{r echo=FALSE, include=TRUE}
  boxplot(totalTime3[totalTime3$Tasks == 'T3', ]$Trials~totalTime3[totalTime3$Tasks == 'T3', ]$Technique+totalTime3[totalTime3$Tasks == 'T3', ]$Tasks,outline=F,
        #ylab="Minutos"
        ylab="Tries"
        )
```

```{r echo=FALSE, include=TRUE}
totalTime2 <- sqldf("select Replica, Id, SetOfTasks, Tasks, 
                    Technique, sum(Trials) as Trials, sum(Minutes) as Time 
                    from ccwocd Where Tasks = 'T3' OR TASKS = 'T6'
                    group by Replica, Id,SetOfTasks, Technique")
totalTime2$Time <-ifelse(totalTime2$Technique == "D", - totalTime2$Time, totalTime2$Time)
totalTime2 <- sqldf("select Id, sum(Time) as Time 
                    from totalTime2 
                    group by Id, Replica")

d <- density(totalTime2$Time) # returns the density data 
plot(d,  xlab="Participantes = 30; Largura de banda = 6.463",
     ylab="Densidade",
     main=expression(T[nd] - T[d]))

```

```{r echo=FALSE, include=TRUE}
  boxplot(totalTime3[totalTime3$Tasks == 'T3', ]$Trials~totalTime3[totalTime3$Tasks == 'T3', ]$Technique+totalTime3[totalTime3$Tasks == 'T3', ]$Tasks,outline=F,
        #ylab="Minutos"
        ylab="Tentativas"
        )
```

```{r include=TRUE}
totalTrials <- sqldf("select Replica, Id, SetOfTasks,
                      Technique, sum(Trials) as Trials
                      from ccwocd where Tasks = 'T3' OR Tasks = 'T6'
                      group by Replica, Id,SetOfTasks, Technique")

totalTrials
totalTrials$Trials <- with(totalTrials, Trials +1)
totalTrials
totalTrials$Trials <- with(totalTrials, log2(Trials))
```

```{r include=TRUE}
totalTrials$Replica = as.factor(totalTrials$Replica)
totalTrials$Id = as.factor(totalTrials$Id)
totalTrials$SetOfTasks = as.factor(totalTrials$SetOfTasks)
totalTrials$Technique = as.factor(totalTrials$Technique)
```

```{r include=TRUE}
summary(aov(Trials ~ Replica + Replica:Id + SetOfTasks + Technique, data=totalTrials))
totalTrials.gvlma = gvlma(lm(Trials ~ Technique, data=totalTrials))
summary(totalTrials.gvlma)
```

```{r include=TRUE}
summary(aov(Trials ~ Technique, data=totalTrials))
```
```{r include=TRUE}
ss = summary(aov(Trials ~ Technique, data=totalTrials))[[1]]$"Sum Sq"
eta.sq = ss[1]/(ss[1] + ss[2])
print(paste0("The eta-squared is ",toString(round(eta.sq,3))))
```

```{r include=TRUE}
q <- TukeyHSD(aov(Trials~Technique, data=totalTrials))
q
```

```{r include=TRUE}
slices <- c(67, 33) 
lbls <- c("Perfectiva", "N達o Perfectiva")
pct <- round(slices/sum(slices)*100)
lbls <- paste(lbls, pct) # add percents to labels 
lbls <- paste(lbls,"%",sep="") # ad % to labels 
pie(slices,labels = lbls, col=rainbow(length(lbls))
  )
```